language: ruby
rvm:
  - 2.0.0
before_install:
  - wget http://sourceforge.net/projects/zaproxy/files/2.3.1/ZAP_2.3.1_Linux.tar.gz/download
  - tar -xvf download
  - git submodule update --init --recursive
before_script:
  - pushd vendor/nodegoat
  - npm install
  - mongo < nodegoat_db_reset.js
  - sed -i 's/\/\/db/db/g' config/env/development.js
  - grunt run &
  - popd
services:
  - mongodb
script:
  - bundle exec zapr --summary --timeout=300 --debug --zap-path $TRAVIS_BUILD_DIR/ZAP_2.3.1/zap.sh http://localhost:5000/
